# Generated by Django 3.1.2 on 2021-02-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
