# Generated by Django 3.1.2 on 2021-02-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='user_color',
            field=models.CharField(choices=[('teal', 'Teal'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('brown', 'Brown'), ('tomato', 'Tomato'), ('steelblue', 'Steel blue'), ('slateblue', 'Slate Blue')], default='teal', max_length=20, null=True),
        ),
    ]
