# Generated by Django 3.1.2 on 2021-02-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210215_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='user_avatar',
            field=models.CharField(choices=[("static 'img/avatar1.png'", 'avatar1'), ("static 'img/avatar1.png'", 'avatar2'), ("static 'img/avatar1.png'", 'avatar3'), ("static 'img/avatar1.png'", 'avatar4'), ("static 'img/avatar1.png'", 'avatar5'), ("static 'img/avatar1.png'", 'avatar6'), ("static 'img/avatar1.png'", 'avatar7'), ("static 'img/avatar1.png'", 'avatar8'), ("static 'img/avatar1.png'", 'avatar9')], default="static 'img/avatar1.png'", max_length=50, null=True),
        ),
    ]
