# Generated by Django 3.1.2 on 2021-02-15 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210215_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoIsWatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_watching', to='profiles.profiles')),
            ],
        ),
    ]
