# Generated by Django 3.1.2 on 2021-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_whoiswatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoiswatching',
            name='person_avatar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
