# Generated by Django 3.1.2 on 2021-02-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_whoiswatching_person_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoiswatching',
            name='user_age',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
