# Generated by Django 3.1.2 on 2021-02-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_whoiswatching_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whoiswatching',
            old_name='user_age',
            new_name='person_age',
        ),
    ]
