# Generated by Django 3.1.2 on 2021-02-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210215_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoiswatching',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_watching', to='profiles.profiles'),
        ),
    ]
