# Generated by Django 3.1.2 on 2021-02-14 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_language', models.CharField(choices=[('?language=en-US', 'English'), ('?language=pt-BR', 'Portugues')], default='?language=en-US', max_length=30)),
                ('user_age', models.CharField(choices=[('1', 'Adult'), ('2', 'Child')], default='1', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
