# Generated by Django 3.1.2 on 2020-12-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField(null=True)),
                ('stars', models.CharField(max_length=255, null=True)),
                ('genre', models.CharField(max_length=255, null=True)),
                ('cover', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
            ],
        ),
    ]
