# Generated by Django 3.1.2 on 2021-01-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210102_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='cover',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='summary',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
