# Generated by Django 3.1.2 on 2021-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210222_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='certification',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='relevance',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
